import os

DATASET_ROOT_DIR = '../ds'

FILE_LIST_PATH_TRAIN = os.path.join(DATASET_ROOT_DIR, 'tr', 'file_name_list.txt')
FILE_LIST_PATH_VALID = os.path.join(DATASET_ROOT_DIR, 'cv', 'file_name_list.txt')
FILE_LIST_PATH_TEST = os.path.join(DATASET_ROOT_DIR, 'tt', 'file_name_list.txt')

WAV_DIR_TRAIN = os.path.join(DATASET_ROOT_DIR, 'tr')
WAV_DIR_VALID = os.path.join(DATASET_ROOT_DIR, 'cv')
WAV_DIR_TEST = os.path.join(DATASET_ROOT_DIR, 'tt')
SAMPLERATE_HZ = 8000

EXPERIMENT_ROOT_DIR = '..\\exp_my\\'
EXPERIMENT_TAG = 'default'

RESUME_TRAINING = False
RESUME_FROM_EPOCH = 10
RESUME_FROM_MODEL_DIR = 'default'

# TRAINING PARAMETERS
BATCH_SIZE = 1
NUM_BATCHES_TRAIN = 1 // BATCH_SIZE
NUM_BATCHES_VALID = 1 // BATCH_SIZE
NUM_EPOCHS = 5
NUM_EPOCHS_FOR_EARLY_STOPPING = 10
OPTIMIZER_CLIP_L2_NORM_VALUE = 5
TRAIN_UTTERANCE_LENGTH_IN_SECONDS = 4
SEPARATE_MAX_UTTERANCE_LENGTH_IN_SECONDS = 4  # WHAM! test set longest WAV file length is 13.4 seconds

# NETWORK PARAMETERS
NETWORK_NUM_FILTERS_IN_ENCODER = 64
NETWORK_ENCODER_FILTER_LENGTH = 2
NETWORK_NUM_UNITS_PER_LSTM = 200
NETWORK_NUM_DPRNN_BLOCKS = 3
NETWORK_CHUNK_SIZE = 256